# Permalinks
#
permalink:           pretty

# Setup
title:               A Grimoire of SPLs
tagline:             World's Okayest Splunk Wizard
url:                 blog.traytonwhite.com
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Trayton White
  url:               https://twitter.com/traytonwhite
  email:             traytonwhite@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/traytonwhite/traytonwhite.github.io
